### ISSUE TITLE
Use capital snake case

### ISSUE THREAD

**Issue by Ayamin0x539** [Catastrio/Twitch-Follower-Grabber#1]
https://github.com/Catastrio/Twitch-Follower-Grabber/blob/e4c177b7c59b3c431e033e6e4d8aad5377917a23/TwitchFollowerGrabber.py#L10

**Comment by Catastrio** [comment]
This_is_capital_snake_case_right?

**Comment by Ayamin0x539** [comment]
No, `THIS_IS_CAPITAL_SNAKE_CASE`. For constants.
