### ISSUE TITLE
Use list comprehension

### ISSUE THREAD

**Issue by Ayamin0x539** [Catastrio/Twitch-Follower-Grabber#10]
https://github.com/Catastrio/Twitch-Follower-Grabber/blob/e4c177b7c59b3c431e033e6e4d8aad5377917a23/TwitchFollowerGrabber.py#L27

Change while loop to use list comprehension. This will also grab all followers. You're putting a self-imposed limit on yourself for 100...

**Comment by Catastrio** [comment]
When I did research on list comprehensions before, a couple of sites I found implied that only for loops could be turned into a list comprehension. I'll have to do more reading on the topic. 

This is a carry over from my past thinking. Twitch's API only allows for 100 results at a time. They use pagination to allow you to get more followers 

Though, as I typed this, now I'm thinking could do list comprehension to go through it and have an if statement to change the path it goes. If length = 100 , store the pagination and go through the list, storing followers else if length < 100, store all of those followers and then finish.

I think I see how to do it, I'm just not explaining it super clearly. I'll probably come back here and comment once I think I've done it right. I also think I might set it up for getting the followers of someone with more than 100 right now just so I can stop thinking about it and do it right the first time.

**Comment by Ayamin0x539** [comment]
Practice with simpler list comprehensions. Knowledge is inductive.

**Comment by Catastrio** [comment]
```
listOfUserIDs = [ID['from_id'] for ID in userFollowersResponse['data']]
```
Done!

**Comment by Catastrio** [comment]
Also, that actually took me 5 minutes to do but I've had a busy night!
