### ISSUE TITLE
Use main exec

### ISSUE THREAD

**Issue by Ayamin0x539** [Catastrio/Twitch-Follower-Grabber#14]
https://github.com/Catastrio/Twitch-Follower-Grabber/blob/e4c177b7c59b3c431e033e6e4d8aad5377917a23/TwitchFollowerGrabber.py#L45

`if name == '__main__'`...

**Comment by Catastrio** [comment]
Switched to: 

if __name__ == '__main__':
    main()

Notes: This is to allow the program to be imported into other programs. I can now import the follower grabber into another program and call its' main method if I desire.

**Comment by Ayamin0x539** [comment]
No, it needs to be `'__main__'`

**Comment by Catastrio** [comment]
That was the result of me not using the markup thing. __Two underscores bolds your stuff like this__ `'__main__'` is what I have now.
