### ISSUE TITLE
Suggest variable name change

### ISSUE THREAD

**Issue by Ayamin0x539** [Catastrio/Twitch-Follower-Grabber#21]
https://github.com/Catastrio/Twitch-Follower-Grabber/blob/8e23ee6b21e11ce4a90a2445dd223691da9fa14d/TwitchFollowerGrabber.py#L23

I just realized, a better name would be `userByUsernameEndpoint`. Because you input a username, and the output is user data. Similarly, on:

https://github.com/Catastrio/Twitch-Follower-Grabber/blob/8e23ee6b21e11ce4a90a2445dd223691da9fa14d/TwitchFollowerGrabber.py#L39

A better name would be `userByUserIdEndpoint`. Because you input a user ID, and the output is user data.

**Comment by Catastrio** [comment]
This makes a lot of sense. I'm actually mad at myself. For some reason "loginName" came to me before "Username" did haha. I like this. A lot more clear.
