### ISSUE TITLE
Don't reuse variable names

### ISSUE THREAD

**Issue by Ayamin0x539** [Catastrio/Twitch-Follower-Grabber#8]
https://github.com/Catastrio/Twitch-Follower-Grabber/blob/e4c177b7c59b3c431e033e6e4d8aad5377917a23/TwitchFollowerGrabber.py#L21

Avoid mutating state as much as possible. Especially when you're writing scripts like this.

**Comment by Catastrio** [comment]
So this was actually a mistake! The result of bad variable names. I didn't mean to reuse the variable, I just was bad and accidentally reused toe variable name haha. This issue was remedied by making all of my variable names more clear.
