### ISSUE TITLE
Pull 0 to constant

### ISSUE THREAD

**Issue by Ayamin0x539** [Catastrio/Twitch-Follower-Grabber#9]
https://github.com/Catastrio/Twitch-Follower-Grabber/blob/e4c177b7c59b3c431e033e6e4d8aad5377917a23/TwitchFollowerGrabber.py#L19

Pull out 0 to a named constant

**Comment by Catastrio** [comment]
https://dev.twitch.tv/docs/api/reference#get-users 

So if you look there, you'll see the example response of what I'm given. 

Data stores an array containing a dictionary right? That's how the JSON object is structured?

So my response is a dictionary.
"data" is the key resulting an array value
0 in this array contains a dictionary.
"id" is the key resulting in a string containing a user's ID.

So pulling 0 out to a named constant seems like it might be confusing. What would be the naming conventions for it? ['data'][DATARESPONSE]['id'] is my best guess but that seems really bad.

**Comment by Ayamin0x539** [comment]
`DATA_INDEX`

**Comment by Ayamin0x539** [comment]
Even better:

```python
data = response['data'][0]
user_id = data['id']
```

**Comment by Catastrio** [comment]
Would I still pull the 0 to the named constant? Or would it be better to do:
`
USERLOGINDATA = response ['data'][0]
user_id = USERLOGINDATA['id']
`
Either way I like that idea. You said avoid mutating state. The user_id in this instance is only one. It's the ID for the login name the user provides. But later on I have this frequently changing. I'll see about incorporating that in both instances.

**Comment by Ayamin0x539** [comment]
Don't make the variable name all caps - it's not a constant. Also you're mutating state by reassigning the same variable within the same scope.
